source/hosts.txt

New submission added in #1 by @Imparium as such will make a new sub-branch to `whamola-patch-1`

Some brazilian porn sites

---

CONTRIBUTING.md
dev-tools/DataTesting.sh

I've added a little more code, to hopefully make it easier for new users to contribute to our sources
Wee will need these two images as well to the new code, and that will require a second modification of the PR to set the right url to images

Enhanged the understanding [skip ci]

---

source/hosts.txt

I have added a new host as in #4 Please add these domains to block list

domain-name.tld

---

CONTRIBUTING.md
dev-tools/DataTesting.sh

Spirillen patch 1 1

---

.travis.yml
submit_here/hosts.txt

```shell
cdn1.bestofsexvids.com
cdn2.bestofsexvids.com
cdn3.bestofsexvids.com
www.bestofsexvids.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1530

bestofsexvids.com

---

submit_here/hosts.txt

```shell
cdn1.bestyoungporn.com
cdn2.bestyoungporn.com
cdn3.bestyoungporn.com
www.bestyoungporn.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1531

bestyoungporn.com

---

submit_here/hosts.txt

```shell
cdn1.bestyoungsex.com
cdn2.bestyoungsex.com
cdn3.bestyoungsex.com
www.bestyoungsex.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1532

bestyoungsex.com

---

submit_here/hosts.txt

```shell
cdn1.fuckteenporn.com
cdn2.fuckteenporn.com
cdn3.fuckteenporn.com
www.fuckteenporn.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1552

fuckteenporn.com

---

submit_here/hosts.txt

```shell
cdn1.freesextube.tv
cdn2.freesextube.tv
cdn3.freesextube.tv
www.freesextube.tv
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1551

freesextube.tv

---

submit_here/hosts.txt

```shell
cdn1.freesextube.su
cdn2.freesextube.su
cdn3.freesextube.su
www.freesextube.su
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1550

freesextube.su

---

submit_here/hosts.txt

```shell
cdn1.freesextube.porn
cdn2.freesextube.porn
cdn3.freesextube.porn
www.freesextube.porn
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1549

freesextube.porn

---

submit_here/hosts.txt

```shell
cdn1.freesexbros.com
cdn2.freesexbros.com
cdn3.freesexbros.com
www.freesexbros.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1548

freesexbros.com

---

submit_here/hosts.txt

```shell
cdn1.freesexbase.com
cdn2.freesexbase.com
cdn3.freesexbase.com
www.freesexbase.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1547

freesexbase.com

---

submit_here/hosts.txt

```shell
cdn1.freesexalbum.com
cdn2.freesexalbum.com
cdn3.freesexalbum.com
www.freesexalbum.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1546

freesexalbum.com

---

submit_here/hosts.txt

Porn CDN for https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1544 `fuckland.xyz`
<details><summary>Logger output</summary>
| | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +67 |  |  | `www.fuckland.xyz` | 3 | image | `https://pornity.xyz/cg/thumbs/112/934_Dane_Nici.jpg` |
| +67 |  |  | `www.fuckland.xyz` | 3 | image | `https://pornity.xyz/cg/thumbs/118/119_Hot_Women.jpg` |
| +67 |  |  | `www.fuckland.xyz` | 3 | image | `https://pornity.xyz/cg/thumbs/178/056_help.jpg` |
| +67 |  |  | `www.fuckland.xyz` | 3 | image | `https://pornity.xyz/cg/thumbs/119/330_milfs_other.jpg` |
| +67 |  |  | `www.fuckland.xyz` | 3 | image | `https://pornity.xyz/cg/thumbs/131/018_blond_need.jpg` |
| +67 |  |  | `www.fuckland.xyz` | 3 | image | `https://pornity.xyz/cg/thumbs/158/052__Hot.jpg` …

pornity.xyz

---

submit_here/hosts.txt

```shell
cdn1.cakepornvids.com
cdn2.cakepornvids.com
cdn3.cakepornvids.com
www.cakepornvids.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1533

cakepornvids.com

---

submit_here/hosts.txt

```shell
cdn1.freesex5.com
cdn2.freesex5.com
cdn3.freesex5.com
www.freesex5.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1542

freesex5.com

---

submit_here/hosts.txt

```shell
cdn1.freepornlab.com
cdn2.freepornlab.com
cdn3.freepornlab.com
www.freepornlab.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1540

freepornlab.com

---

submit_here/hosts.txt

```shell
cdn1.freemilfs.porn
cdn2.freemilfs.porn
cdn3.freemilfs.porn
www.freemilfs.porn
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1539

freemilfs.porn

---

submit_here/hosts.txt

```shell
cdn1.freesex.pro
cdn2.freesex.pro
cdn3.freesex.pro
www.freesex.pro
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1541

freesex.pro

---

submit_here/hosts.txt

```shell
cdn1.freeadulter.com
cdn2.freeadulter.com
cdn3.freeadulter.com
www.freeadulter.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1538

freeadulter.com

---

submit_here/hosts.txt

```shell
cdn1.duxporn.com
cdn2.duxporn.com
cdn3.duxporn.com
www.duxporn.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1537

duxporn.com

---

submit_here/hosts.txt

```shell
cdn1.crystalxxxporn.com
cdn2.crystalxxxporn.com
cdn3.crystalxxxporn.com
www.crystalxxxporn.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1536

crystalxxxporn.com

---

submit_here/hosts.txt

```shell
cdn1.chicksextube.com
cdn2.chicksextube.com
cdn3.chicksextube.com
www.chicksextube.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1535

chicksextube.com

---

submit_here/hosts.txt

```shell
cdn1.cherrypornhd.com
cdn2.cherrypornhd.com
cdn3.cherrypornhd.com
www.cherrypornhd.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1534

cherrypornhd.com

---

submit_here/hosts.txt

hoxporn.com
www.hoxporn.com
cdn1.hoxporn.com
cdn2.hoxporn.com
cdn3.hoxporn.com
</details>

hoxporn.com

---

submit_here/hosts.txt

```shell
cdn1.avisex.net
cdn2.avisex.net
cdn3.avisex.net
www.avisex.net
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1523

avisex.net

---

submit_here/hosts.txt

```shell
cdn1.bestfreesexporn.net
cdn2.bestfreesexporn.net
cdn3.bestfreesexporn.net
www.bestfreesexporn.net
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1529

bestfreesexporn.net

---

submit_here/hosts.txt

```shell
cdn1.bestfreesexporn.com
cdn2.bestfreesexporn.com
cdn3.bestfreesexporn.com
www.bestfreesexporn.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1528

bestfreesexporn.com

---

submit_here/hosts.txt

```shell
cdn1.best-sex-vids.com
cdn2.best-sex-vids.com
cdn3.best-sex-vids.com
www.best-sex-vids.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1527

best-sex-vids.com

---

submit_here/hosts.txt

```shell
cdn1.basepornxxx.com
cdn2.basepornxxx.com
cdn3.basepornxxx.com
www.basepornxxx.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1524

basepornxxx.com

---

submit_here/hosts.txt

```shell
cdn1.angryvids.com
cdn2.angryvids.com
cdn3.angryvids.com
www.angryvids.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1522

angryvids.com

---

submit_here/hosts.txt

Added three CDN's for `best-porn-clips.com`

`best-porn-clips.com`

---

submit_here/hosts.txt

```python
dirtyxporn.com
cdn1.dirtyxporn.com
cdn2.dirtyxporn.com
cdn3.dirtyxporn.com
www.dirtyxporn.com
```
</details>
This porn domain will be merged by !259
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1503

dirtyxporn.com

---

submit_here/hosts.txt

https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1505

flexyvids.com

---

submit_here/hosts.txt

```shell
www.gratsporn.com
cdn1.gratsporn.com
cdn2.gratsporn.com
cdn3.gratsporn.com
```
</details>

gratsporn.com

---

submit_here/hosts.txt

```shell
cdn1.luxporntube.com
cdn2.luxporntube.com
cdn3.luxporntube.com
www.luxporntube.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1510

luxporntube.com

---

submit_here/hosts.txt

```shell
cdn1.porn-24h.com
cdn2.porn-24h.com
cdn3.porn-24h.com
www.porn-24h.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1511

porn-24h.com

---

submit_here/hosts.txt

```shell
cdn1.porn-x-porn.com
cdn2.porn-x-porn.com
cdn3.porn-x-porn.com
wwww.porn-x-porn.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1511

porn-x-porn.com

---

submit_here/hosts.txt

```shell
cdn1.porn-xxx-videos.com
cdn2.porn-xxx-videos.com
cdn3.porn-xxx-videos.com
www.porn-xxx-videos.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1513

porn-xxx-videos.com

---

submit_here/hosts.txt

```shell
cdn1.porncase.tv
cdn2.porncase.tv
cdn3.porncase.tv
www.porncase.tv
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1514

porncase.tv

---

submit_here/hosts.txt

```shell
cdn1.porntool.net
cdn2.porntool.net
cdn3.porntool.net
www.porntool.net
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1515

porntool.net

---

submit_here/hosts.txt

```shell
cdn1.pornwhy.com
cdn2.pornwhy.com
cdn3.pornwhy.com
www.pornwhy.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1516

`pornwhy.com`

---

submit_here/hosts.txt

```shell
cdn1.readyforporn.com
cdn2.readyforporn.com
cdn3.readyforporn.com
www.readyforporn.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1517

readyforporn.com

---

submit_here/hosts.txt

```shell
cdn1.sexposetube.com
cdn2.sexposetube.com
cdn3.sexposetube.com
www.sexposetube.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1518

sexposetube.com

---

submit_here/hosts.txt

```shell
cdn1.umalix.com
cdn2.umalix.com
cdn3.umalix.com
www.umalix.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1519

umalix.com

---

submit_here/hosts.txt

```shell
cdn1.ahporntube.com
cdn2.ahporntube.com
cdn3.ahporntube.com
www.ahporntube.com
```
</details>
https://gitlab.com/my-privacy-dns/matrix/matrix/issues/1521

ahporntube.com

---

submit_here/hosts.txt

A hole bunch of new and veryfied adult(porn) domains and there CDN's to actually do real adult contents blocking

Submissions April 2020

---

.github/ISSUE_TEMPLATE/mass-submit.md
.github/ISSUE_TEMPLATE/removal-request.md
.github/ISSUE_TEMPLATE/snuff.md
submit_here/hosts.txt

Have added a couple of domains.
Have fixed a merge error where a previously fix of the issue templates was discarded
[asianteengirls.net](https://app.gitkraken.com/glo/board/5e907ff432fc5c002997a0b3/card/5e956d0f192bfb002e75b357)
[asiansgoporn.com](https://app.gitkraken.com/glo/board/5e907ff432fc5c002997a0b3/card/5e956ca5192bfb002e75b33d)

Few domains, Mostly fixed issue templates

---

submit_here/hosts.txt

Closes https://github.com/Import-External-Sources/pornhosts/issues/656

cambuilder.com

---

submit_here/hosts.txt

---
name: literoticavod.com
about: I would like to contribute with the following domain to the hosts file
title: 'Type only domain here'
labels: NSFW Adult Material
assignees: spirillen
reviewers: Clefspeare13, Spirillen
projects: https://github.com/orgs/Import-External-Sources/projects/2
---
```python
literoticavod.com
www.literoticavod.com
```
</details>

literoticavod.com

---

submit_here/hosts.txt

---
name: default
about: I would like to contribute with the following domain to the hosts file
title: 'Type only domain here'
labels: NSFW Adult Material
assignees: spirillen
reviewers: Clefspeare13, Spirillen
projects: https://github.com/orgs/Import-External-Sources/projects/2
---
```python
searchcelebrityhd.com
www.searchcelebrityhd.com
```
</details>
https://github.com/Sinfonietta/hostfiles/issues/98#issuecomment-639232135

searchcelebrityhd.com

---

submit_here/hosts.txt

---
name: literotica.com
about: I would like to contribute with the following domain to the hosts file
title: literotica.com
labels: NSFW Adult Material
assignees: spirillen
reviewers: Clefspeare13, Spirillen
projects: https://github.com/orgs/Import-External-Sources/projects/2
---
```python
literotica.com
shop.literotica.com
vipcams.literotica.com
forum.literotica.com
www.literotica.com
www.shop.literotica.com
www.vipcams.literotica.com
www.forum.literotica.com
```
</details>

literotica.com

---

submit_here/hosts.txt

---
name: default
about: I would like to contribute with the following domain to the hosts file
title: 'Type only domain here'
labels: NSFW Adult Material
assignees: spirillen
reviewers: Clefspeare13, Spirillen
projects: https://github.com/orgs/Import-External-Sources/projects/2
---
```python
viewgals.com
www.viewgals.com
```
</details>
https://github.com/Sinfonietta/hostfiles/issues/98#issuecomment-639232135

viewgals.com

---

submit_here/hosts.txt

```python
images.securedataimages.com
```
<details><summary>Logger output</summary>
| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +867 |  |  | streamray.com | 3 | image | `https://cs891.wac.systemcdn.net/` | `aliasURL=https://images.securedataimages.com/photo-cams-r40-s2-b711655.3592767._640.gif` |
| +867 |  |  | streamray.com | 3 | image | `https://images.securedataimages.com/photo-cams-r40-s2-b711655.3592767._640.gif` |
| +867 |  |  | streamray.com | 3 | image | `https://cs891.wac.systemcdn.net/` | `aliasURL=https://images.securedataimages.com/photo-cams-r40-s2-b707464.3574586._640.gif` |
| +867 |  |  | streamray.com | 3 | image | …

`securedataimages.com`

---

submit_here/hosts.txt

```python
streamray.com
images1.streamray.com
images2.streamray.com
images3.streamray.com
images4.streamray.com
partners.streamray.com
```
Other related domains:
```
cs891.wac.systemcdn.net
images.securedataimages.com
```
</details>
<details><summary>Logger output</summary>
| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +20 |  |  | vipcams.literotica.com | 3 | xhr | `https://partners.streamray.com/` | `aliasURL=https://vipcams.literotica.com/p/cams/chat.cgi?type=log&code=8888&handle=Literotica-Cams&callback=recTPLog&rid=1594392263087&` |
| +18 |  |  | vipcams.literotica.com | 3 | image | `https://partners.streamray.com/` | …

`streamray.com`

---

submit_here/hosts.txt

I believe this domain is an Adult(-related) domain --> that have to be blocked as..
```python
videothumb.gammacdn.com
transform.gammacdn.com
static01-cms-fame.gammacdn.com
static02-cms-fame.gammacdn.com
static03-cms-fame.gammacdn.com
images01-fame.gammacdn.com
images02-fame.gammacdn.com
images03-fame.gammacdn.com
images04-fame.gammacdn.com
```
This domain is the CDN for all of 21naturals network
<details><summary>Logger output</summary>
| | | | | | | | |
|:--- |:--- |:--- |:--- |:--- |:--- |:--- |:--- |
| +170 |  |  | `www.21naturals.com` | 3 | media | `https://d1inoy3qg3jcr8.cloudfront.net/` | `aliasURL=https://videothumb.gammacdn.com/600x339/170852.mp4` |
| +170 |  |  | `www.21naturals.com` | 3 | media | `https://videothumb.gammacdn.com/600x339/170852.mp4` |
| +169 |  |  | …

gammacdn.com

---

submit_here/hosts.txt

```python
cdn1.zzbabes.com
cdn2.zzbabes.com
cdn3.zzbabes.com
zzbabes.com
www.zzbabes.com
```
</details>
- https://github.com/Import-External-Sources/pornhosts/pull/677
- https://www.mypdns.org/T956

zzbabes.com

---

submit_here/hosts.txt

```python
sex-vip.com
www.sex-vip.com
```
</details>

sex-vip.com

---

submit_here/hosts.txt

```python
f95zone.to
www.f95zone.to
static.f95zone.to
attachments.f95zone.to
```
</details>
forum to share porn

f95zone.to

---

submit_here/hosts.txt

```python
baixarhentai.net
leitura.baixarhentai.net
```
</details>

baixarhentai.net

---

submit_here/hosts.txt

```python
sankakucomplex.com
beta.sankakucomplex.com
chan.sankakucomplex.com
idol.sankakucomplex.com
www.sankakucomplex.com
```
</details>

sankakucomplex.com

---

submit_here/hosts.txt

```python
www.xvideos.com
img-hw.xvideos-cdn.com
static-l3.xvideos-cdn.com
cdn77-pic.xvideos-cdn.com
img-l3.xvideos-cdn.com
hls2-l3.xvideos-cdn.com
hls3-l3.xvideos-cdn.com
hls1-l3.xvideos-cdn.com
hls-hw.xvideos-cdn.com
img100-321.xvideos.com
```
this is all i could find, i think there is more to be found, maybe with some more help the list can be completed
</details>

xvideos.com

---

submit_here/hosts.txt

```python
www.pornoeggs.com
cdn-img1.pornoeggs.com
```
</details>
https://github.com/Clefspeare13/pornhosts/issues/51#issue-483093784

pornoeggs.com

---

submit_here/hosts.txt

```python
www.sicflics.com
images.sicflics.com
members.sicflics.com
join.sicflics.com
```
</details>

sicflics.com

---

submit_here/hosts.txt

```python
equibooru.tk
```
</details>

equibooru.tk

---

submit_here/hosts.txt

```python
equi-booru.gq
```
copy of equibooru.tk
https://github.com/Import-External-Sources/pornhosts/pull/781#issue-465080512
</details>

equi-booru.gq

---

submit_here/hosts.txt

```python
www.monpornofrancais.com
```
</details>

monpornofrancais.com

---

submit_here/hosts.txt

```python
s-hentai.com
```
</details>

s-hentai.com

---

submit_here/hosts.txt

```python
nsk.erobodio.com
erobodio.com
```
See @DaniV5 cimmits at <https://github.com/Clefspeare13/pornhosts/pull/175> and <https://github.com/Clefspeare13/pornhosts/pull/175>

erobodio.com

---

submit_here/hosts.txt

```python
animopron.com
```
</details>

animopron.com

---

submit_here/hosts.txt

```python
ohentai.org
```
ohentai2016.disqus.com
</details>

ohentai.org
